name: Docker Image CI

on:
  push:
    tags:
    - 'v*.*.*'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: >
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rss-feed-demo:${{  github.ref_name }}
    - name: Docker Push
      run: docker image push ${{ secrets.DOCKER_USER }}/rss-feed-demo/rss-feed-demo:${{  github.ref_name }}
